///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EPM.CRM.PQR.Funcionalidad001_Inicio
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BuscarEntidadCasos recording.
    /// </summary>
    [TestModule("54d817de-c477-4d41-a3eb-966446c83452", ModuleType.Recording, 1)]
    public partial class BuscarEntidadCasos : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EPM.CRM.PQR.EPM_CRM_PQRRepository repository.
        /// </summary>
        public static EPM.CRM.PQR.EPM_CRM_PQRRepository repo = EPM.CRM.PQR.EPM_CRM_PQRRepository.Instance;

        static BuscarEntidadCasos instance = new BuscarEntidadCasos();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BuscarEntidadCasos()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BuscarEntidadCasos Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PanelesInformacionGeneralDeMicrosof.TabWorkplace' at 19;33.", repo.PanelesInformacionGeneralDeMicrosof.TabWorkplaceInfo, new RecordItemIndex(0));
            repo.PanelesInformacionGeneralDeMicrosof.TabWorkplace.Click("19;33");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PanelesInformacionGeneralDeMicrosof.Servicio' at 11;33.", repo.PanelesInformacionGeneralDeMicrosof.ServicioInfo, new RecordItemIndex(1));
            repo.PanelesInformacionGeneralDeMicrosof.Servicio.Click("11;33");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PanelesInformacionGeneralDeMicrosof.Casos' at 29;16.", repo.PanelesInformacionGeneralDeMicrosof.CasosInfo, new RecordItemIndex(2));
            repo.PanelesInformacionGeneralDeMicrosof.Casos.Click("29;16");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
