///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EPM.CRM.PQR.Funcionalidad001_Inicio
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The IngresaDatosQueja recording.
    /// </summary>
    [TestModule("3d85cdb8-4bab-4058-9bc4-e650b6aa780e", ModuleType.Recording, 1)]
    public partial class IngresaDatosQueja : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EPM.CRM.PQR.EPM_CRM_PQRRepository repository.
        /// </summary>
        public static EPM.CRM.PQR.EPM_CRM_PQRRepository repo = EPM.CRM.PQR.EPM_CRM_PQRRepository.Instance;

        static IngresaDatosQueja instance = new IngresaDatosQueja();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public IngresaDatosQueja()
        {
            pps = "CL 98 C CR 80 C -30";
            vNumRadicado = "20180120032908";
            vServicioSuscrito = "1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static IngresaDatosQueja Instance
        {
            get { return instance; }
        }

#region Variables

        string _pps;

        /// <summary>
        /// Gets or sets the value of variable pps.
        /// </summary>
        [TestVariable("3ec8d762-3195-4957-856f-3a9fc0d4d143")]
        public string pps
        {
            get { return _pps; }
            set { _pps = value; }
        }

        string _vNumRadicado;

        /// <summary>
        /// Gets or sets the value of variable vNumRadicado.
        /// </summary>
        [TestVariable("ae742ade-ce44-417c-bf42-8c7240f653a8")]
        public string vNumRadicado
        {
            get { return _vNumRadicado; }
            set { _vNumRadicado = value; }
        }

        string _vServicioSuscrito;

        /// <summary>
        /// Gets or sets the value of variable vServicioSuscrito.
        /// </summary>
        [TestVariable("a7d2365a-ac7e-4b27-b5aa-ce100b79d00a")]
        public string vServicioSuscrito
        {
            get { return _vServicioSuscrito; }
            set { _vServicioSuscrito = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 400;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CasoNuevoCaso.EpmPqrservicepointidLedit' at 144;11.", repo.CasoNuevoCaso.EpmPqrservicepointidLeditInfo, new RecordItemIndex(0));
            //repo.CasoNuevoCaso.EpmPqrservicepointidLedit.Click("144;11", 300);
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(1));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$pps'.", new RecordItemIndex(2));
            Keyboard.Press(pps);
            Delay.Milliseconds(10);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(3));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Up}{Return}'.", new RecordItemIndex(4));
            Keyboard.Press("{Down}{Up}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(5));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MessageFromWebpage.ButtonOK' at 38;9.", repo.MessageFromWebpage.ButtonOKInfo, new RecordItemIndex(6));
            repo.MessageFromWebpage.ButtonOK.Click("38;9", 300);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CasoNuevoCaso.ContentIFrame1.MsCrmInlineValueMsCrmInlineLookup1' at 59;9.", repo.CasoNuevoCaso.ContentIFrame1.MsCrmInlineValueMsCrmInlineLookup1Info, new RecordItemIndex(7));
            repo.CasoNuevoCaso.ContentIFrame1.MsCrmInlineValueMsCrmInlineLookup1.Click("59;9", 300);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(8));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Up}{Return}'.", new RecordItemIndex(9));
            Keyboard.Press("{Down}{Up}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue='') on item 'CasoNuevoCaso.ContentIFrame1.DireccionDeRespuestaLabel'.", repo.CasoNuevoCaso.ContentIFrame1.DireccionDeRespuestaLabelInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.CasoNuevoCaso.ContentIFrame1.DireccionDeRespuestaLabelInfo, "TagValue", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue='') on item 'CasoNuevoCaso.ContentIFrame1.DepartamentoDeRespuestaLabel'.", repo.CasoNuevoCaso.ContentIFrame1.DepartamentoDeRespuestaLabelInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.CasoNuevoCaso.ContentIFrame1.DepartamentoDeRespuestaLabelInfo, "TagValue", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue='') on item 'CasoNuevoCaso.ContentIFrame1.MunicipioDeRespuestaLabel'.", repo.CasoNuevoCaso.ContentIFrame1.MunicipioDeRespuestaLabelInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.CasoNuevoCaso.ContentIFrame1.MunicipioDeRespuestaLabelInfo, "TagValue", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CasoNuevoCaso.ContentIFrame1.MsCrmInlineValueMsCrmInlineHasErr' at 25;14.", repo.CasoNuevoCaso.ContentIFrame1.MsCrmInlineValueMsCrmInlineHasErrInfo, new RecordItemIndex(13));
            repo.CasoNuevoCaso.ContentIFrame1.MsCrmInlineValueMsCrmInlineHasErr.Click("25;14", 300);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '3'.", new RecordItemIndex(14));
            Keyboard.Press("3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CasoNuevoCaso.ContentIFrame1.MsCrmInlineValueMsCrmInlineEditHi' at 46;11.", repo.CasoNuevoCaso.ContentIFrame1.MsCrmInlineValueMsCrmInlineEditHiInfo, new RecordItemIndex(15));
            repo.CasoNuevoCaso.ContentIFrame1.MsCrmInlineValueMsCrmInlineEditHi.Click("46;11", 300);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1'.", new RecordItemIndex(16));
            Keyboard.Press("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CasoNuevoCaso.ContentIFrame1.DivTag70daedd7Aebd46953c5aCbb022d4e' at 744;25.", repo.CasoNuevoCaso.ContentIFrame1.DivTag70daedd7Aebd46953c5aCbb022d4eInfo, new RecordItemIndex(17));
            repo.CasoNuevoCaso.ContentIFrame1.DivTag70daedd7Aebd46953c5aCbb022d4e.Click("744;25", 300);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Se ha presentado un inconveniente de negocio en el aprovisionador: El radicado no existe en la base de datos.') on item 'MessageFromWebpage.Text65535'.", repo.MessageFromWebpage.Text65535Info, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.MessageFromWebpage.Text65535Info, "Text", "Se ha presentado un inconveniente de negocio en el aprovisionador: El radicado no existe en la base de datos.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (WindowText='Se ha presentado un inconveniente de negocio en el aprovisionador: El radicado no existe en la base de datos.') on item 'MessageFromWebpage.Text65535'.", repo.MessageFromWebpage.Text65535Info, new RecordItemIndex(19));
            Validate.AttributeEqual(repo.MessageFromWebpage.Text65535Info, "WindowText", "Se ha presentado un inconveniente de negocio en el aprovisionador: El radicado no existe en la base de datos.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MessageFromWebpage.ButtonOK' at 44;16.", repo.MessageFromWebpage.ButtonOKInfo, new RecordItemIndex(20));
            repo.MessageFromWebpage.ButtonOK.Click("44;16", 300);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CasoNuevoCaso.ContentIFrame1.EpmPqrfilenumberI' at 133;16.", repo.CasoNuevoCaso.ContentIFrame1.EpmPqrfilenumberIInfo, new RecordItemIndex(21));
            repo.CasoNuevoCaso.ContentIFrame1.EpmPqrfilenumberI.Click("133;16", 300);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$vNumRadicado' with focus on 'CasoNuevoCaso.ContentIFrame1.EpmPqrfilenumberI'.", repo.CasoNuevoCaso.ContentIFrame1.EpmPqrfilenumberIInfo, new RecordItemIndex(22));
            repo.CasoNuevoCaso.ContentIFrame1.EpmPqrfilenumberI.PressKeys(vNumRadicado);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CasoNuevoCaso.ContentIFrame1.MotivoPQRDetalleLabel' at 55;15.", repo.CasoNuevoCaso.ContentIFrame1.MotivoPQRDetalleLabelInfo, new RecordItemIndex(23));
            repo.CasoNuevoCaso.ContentIFrame1.MotivoPQRDetalleLabel.Click("55;15", 300);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'xxxxxxx'.", new RecordItemIndex(24));
            Keyboard.Press("xxxxxxx");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
