///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EPM.CRM.PQR.Funcionalidad001_Inicio
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SeleccionaFormularioQuejas recording.
    /// </summary>
    [TestModule("6c0e8838-555a-496c-9e0b-b6b9a2811891", ModuleType.Recording, 1)]
    public partial class SeleccionaFormularioQuejas : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EPM.CRM.PQR.EPM_CRM_PQRRepository repository.
        /// </summary>
        public static EPM.CRM.PQR.EPM_CRM_PQRRepository repo = EPM.CRM.PQR.EPM_CRM_PQRRepository.Instance;

        static SeleccionaFormularioQuejas instance = new SeleccionaFormularioQuejas();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SeleccionaFormularioQuejas()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SeleccionaFormularioQuejas Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CasoNuevoCaso.ContentIFrame1.FormSelectorDropdown' at 7;15.", repo.CasoNuevoCaso.ContentIFrame1.FormSelectorDropdownInfo, new RecordItemIndex(0));
            repo.CasoNuevoCaso.ContentIFrame1.FormSelectorDropdown.Click("7;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CasoNuevoCaso.ContentIFrame1.Quejas' at 24;11.", repo.CasoNuevoCaso.ContentIFrame1.QuejasInfo, new RecordItemIndex(1));
            repo.CasoNuevoCaso.ContentIFrame1.Quejas.Click("24;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MessageFromWebpage.ButtonOK' at 29;9.", repo.MessageFromWebpage.ButtonOKInfo, new RecordItemIndex(2));
            repo.MessageFromWebpage.ButtonOK.Click("29;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MessageFromWebpage.ButtonOK' at 40;9.", repo.MessageFromWebpage.ButtonOKInfo, new RecordItemIndex(3));
            repo.MessageFromWebpage.ButtonOK.Click("40;9");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
