///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace EPM.CRM.PQR
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the EPM_CRM_PQRRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("6b31eb5c-b88b-46d6-82f0-e05706f49ca1")]
    public partial class EPM_CRM_PQRRepository : RepoGenBaseFolder
    {
        static EPM_CRM_PQRRepository instance = new EPM_CRM_PQRRepository();
        EPM_CRM_PQRRepositoryFolders.PanelesInformacionGeneralDeMicrosofAppFolder _panelesinformaciongeneraldemicrosof;
        EPM_CRM_PQRRepositoryFolders.CasosMisCasosActivosMedioVerbalMAppFolder _casosmiscasosactivosmedioverbalm;
        EPM_CRM_PQRRepositoryFolders.MessageFromWebpageAppFolder _messagefromwebpage;
        EPM_CRM_PQRRepositoryFolders.CasoNuevoCasoAppFolder _casonuevocaso;

        /// <summary>
        /// Gets the singleton class instance representing the EPM_CRM_PQRRepository element repository.
        /// </summary>
        [RepositoryFolder("6b31eb5c-b88b-46d6-82f0-e05706f49ca1")]
        public static EPM_CRM_PQRRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public EPM_CRM_PQRRepository() 
            : base("EPM_CRM_PQRRepository", "/", null, 0, false, "6b31eb5c-b88b-46d6-82f0-e05706f49ca1", ".\\RepositoryImages\\EPM_CRM_PQRRepository6b31eb5c.rximgres")
        {
            _panelesinformaciongeneraldemicrosof = new EPM_CRM_PQRRepositoryFolders.PanelesInformacionGeneralDeMicrosofAppFolder(this);
            _casosmiscasosactivosmedioverbalm = new EPM_CRM_PQRRepositoryFolders.CasosMisCasosActivosMedioVerbalMAppFolder(this);
            _messagefromwebpage = new EPM_CRM_PQRRepositoryFolders.MessageFromWebpageAppFolder(this);
            _casonuevocaso = new EPM_CRM_PQRRepositoryFolders.CasoNuevoCasoAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6b31eb5c-b88b-46d6-82f0-e05706f49ca1")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The PanelesInformacionGeneralDeMicrosof folder.
        /// </summary>
        [RepositoryFolder("50b86fb2-c130-4ba9-a180-c1554d60032b")]
        public virtual EPM_CRM_PQRRepositoryFolders.PanelesInformacionGeneralDeMicrosofAppFolder PanelesInformacionGeneralDeMicrosof
        {
            get { return _panelesinformaciongeneraldemicrosof; }
        }

        /// <summary>
        /// The CasosMisCasosActivosMedioVerbalM folder.
        /// </summary>
        [RepositoryFolder("5c5f2ae1-7058-44ff-a0cf-ebb333035b54")]
        public virtual EPM_CRM_PQRRepositoryFolders.CasosMisCasosActivosMedioVerbalMAppFolder CasosMisCasosActivosMedioVerbalM
        {
            get { return _casosmiscasosactivosmedioverbalm; }
        }

        /// <summary>
        /// The MessageFromWebpage folder.
        /// </summary>
        [RepositoryFolder("418244d2-d97e-4b4e-bb8f-233511365e6d")]
        public virtual EPM_CRM_PQRRepositoryFolders.MessageFromWebpageAppFolder MessageFromWebpage
        {
            get { return _messagefromwebpage; }
        }

        /// <summary>
        /// The CasoNuevoCaso folder.
        /// </summary>
        [RepositoryFolder("b20517ec-cd05-4087-88bf-cd17704f559b")]
        public virtual EPM_CRM_PQRRepositoryFolders.CasoNuevoCasoAppFolder CasoNuevoCaso
        {
            get { return _casonuevocaso; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class EPM_CRM_PQRRepositoryFolders
    {
        /// <summary>
        /// The PanelesInformacionGeneralDeMicrosofAppFolder folder.
        /// </summary>
        [RepositoryFolder("50b86fb2-c130-4ba9-a180-c1554d60032b")]
        public partial class PanelesInformacionGeneralDeMicrosofAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _butbeginInfo;
            RepoItemInfo _tabworkplaceInfo;
            RepoItemInfo _servicioInfo;
            RepoItemInfo _casosInfo;

            /// <summary>
            /// Creates a new PanelesInformacionGeneralDeMicrosof  folder.
            /// </summary>
            public PanelesInformacionGeneralDeMicrosofAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PanelesInformacionGeneralDeMicrosof", "/dom[@domain='epm-wt57' and @caption~'^Paneles:\\ Información\\ gene']", parentFolder, 30000, null, false, "50b86fb2-c130-4ba9-a180-c1554d60032b", "")
            {
                _butbeginInfo = new RepoItemInfo(this, "ButBegin", ".//iframe[#'InlineDialog_Iframe']//button[#'butBegin']", 30000, null, "6169798e-6cf6-493b-9c5f-1ca02ad69c09");
                _tabworkplaceInfo = new RepoItemInfo(this, "TabWorkplace", ".//span[#'TabWorkplace']", 30000, null, "35c1290d-045e-43f7-ab33-f25b84e3b33a");
                _servicioInfo = new RepoItemInfo(this, "Servicio", ".//a[#'CS']//img[@alt='Servicio']", 30000, null, "91c4ea05-e0a5-4fc1-aaff-552cf1e124b7");
                _casosInfo = new RepoItemInfo(this, "Casos", ".//a[#'nav_cases']/span[@innertext='Casos']", 30000, null, "b39651c3-1d50-4f8e-a0cc-8767ce9568bc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("50b86fb2-c130-4ba9-a180-c1554d60032b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("50b86fb2-c130-4ba9-a180-c1554d60032b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButBegin item.
            /// </summary>
            [RepositoryItem("6169798e-6cf6-493b-9c5f-1ca02ad69c09")]
            public virtual Ranorex.ButtonTag ButBegin
            {
                get
                {
                    return _butbeginInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButBegin item info.
            /// </summary>
            [RepositoryItemInfo("6169798e-6cf6-493b-9c5f-1ca02ad69c09")]
            public virtual RepoItemInfo ButBeginInfo
            {
                get
                {
                    return _butbeginInfo;
                }
            }

            /// <summary>
            /// The TabWorkplace item.
            /// </summary>
            [RepositoryItem("35c1290d-045e-43f7-ab33-f25b84e3b33a")]
            public virtual Ranorex.SpanTag TabWorkplace
            {
                get
                {
                    return _tabworkplaceInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TabWorkplace item info.
            /// </summary>
            [RepositoryItemInfo("35c1290d-045e-43f7-ab33-f25b84e3b33a")]
            public virtual RepoItemInfo TabWorkplaceInfo
            {
                get
                {
                    return _tabworkplaceInfo;
                }
            }

            /// <summary>
            /// The Servicio item.
            /// </summary>
            [RepositoryItem("91c4ea05-e0a5-4fc1-aaff-552cf1e124b7")]
            public virtual Ranorex.ImgTag Servicio
            {
                get
                {
                    return _servicioInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Servicio item info.
            /// </summary>
            [RepositoryItemInfo("91c4ea05-e0a5-4fc1-aaff-552cf1e124b7")]
            public virtual RepoItemInfo ServicioInfo
            {
                get
                {
                    return _servicioInfo;
                }
            }

            /// <summary>
            /// The Casos item.
            /// </summary>
            [RepositoryItem("b39651c3-1d50-4f8e-a0cc-8767ce9568bc")]
            public virtual Ranorex.SpanTag Casos
            {
                get
                {
                    return _casosInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Casos item info.
            /// </summary>
            [RepositoryItemInfo("b39651c3-1d50-4f8e-a0cc-8767ce9568bc")]
            public virtual RepoItemInfo CasosInfo
            {
                get
                {
                    return _casosInfo;
                }
            }
        }

        /// <summary>
        /// The CasosMisCasosActivosMedioVerbalMAppFolder folder.
        /// </summary>
        [RepositoryFolder("5c5f2ae1-7058-44ff-a0cf-ebb333035b54")]
        public partial class CasosMisCasosActivosMedioVerbalMAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _spantagcasonuevoInfo;

            /// <summary>
            /// Creates a new CasosMisCasosActivosMedioVerbalM  folder.
            /// </summary>
            public CasosMisCasosActivosMedioVerbalMAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CasosMisCasosActivosMedioVerbalM", "/dom[@caption~'^Casos\\ Mis\\ casos\\ activos\\ m']", parentFolder, 30000, null, false, "5c5f2ae1-7058-44ff-a0cf-ebb333035b54", "")
            {
                _spantagcasonuevoInfo = new RepoItemInfo(this, "SpanTagCasoNuevo", ".//li[#'incident|NoRelationship|HomePageGrid|Mscrm.HomepageGrid.incident.NewRecord']/span", 30000, null, "f724f33c-2d2f-471b-8879-f843bc672699");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5c5f2ae1-7058-44ff-a0cf-ebb333035b54")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5c5f2ae1-7058-44ff-a0cf-ebb333035b54")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SpanTagCasoNuevo item.
            /// </summary>
            [RepositoryItem("f724f33c-2d2f-471b-8879-f843bc672699")]
            public virtual Ranorex.SpanTag SpanTagCasoNuevo
            {
                get
                {
                    return _spantagcasonuevoInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagCasoNuevo item info.
            /// </summary>
            [RepositoryItemInfo("f724f33c-2d2f-471b-8879-f843bc672699")]
            public virtual RepoItemInfo SpanTagCasoNuevoInfo
            {
                get
                {
                    return _spantagcasonuevoInfo;
                }
            }
        }

        /// <summary>
        /// The MessageFromWebpageAppFolder folder.
        /// </summary>
        [RepositoryFolder("418244d2-d97e-4b4e-bb8f-233511365e6d")]
        public partial class MessageFromWebpageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _text65535Info;

            /// <summary>
            /// Creates a new MessageFromWebpage  folder.
            /// </summary>
            public MessageFromWebpageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MessageFromWebpage", "/form[@title='Message from webpage']", parentFolder, 30000, null, true, "418244d2-d97e-4b4e-bb8f-233511365e6d", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='OK']", 30000, null, "2535fe5f-7642-4d0c-b831-eb0c84b70884");
                _text65535Info = new RepoItemInfo(this, "Text65535", "text[@controlid='65535']", 30000, null, "9934b84a-01c9-45f5-abf9-44cc80b093af");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("418244d2-d97e-4b4e-bb8f-233511365e6d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("418244d2-d97e-4b4e-bb8f-233511365e6d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("2535fe5f-7642-4d0c-b831-eb0c84b70884")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("2535fe5f-7642-4d0c-b831-eb0c84b70884")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The Text65535 item.
            /// </summary>
            [RepositoryItem("9934b84a-01c9-45f5-abf9-44cc80b093af")]
            public virtual Ranorex.Text Text65535
            {
                get
                {
                    return _text65535Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text65535 item info.
            /// </summary>
            [RepositoryItemInfo("9934b84a-01c9-45f5-abf9-44cc80b093af")]
            public virtual RepoItemInfo Text65535Info
            {
                get
                {
                    return _text65535Info;
                }
            }
        }

        /// <summary>
        /// The CasoNuevoCasoAppFolder folder.
        /// </summary>
        [RepositoryFolder("b20517ec-cd05-4087-88bf-cd17704f559b")]
        public partial class CasoNuevoCasoAppFolder : RepoGenBaseFolder
        {
            EPM_CRM_PQRRepositoryFolders.ContentIFrame1Folder _contentiframe1;
            RepoItemInfo _epmpqrservicepointidleditInfo;

            /// <summary>
            /// Creates a new CasoNuevoCaso  folder.
            /// </summary>
            public CasoNuevoCasoAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CasoNuevoCaso", "/dom[@caption='Caso: Nuevo Caso']", parentFolder, 30000, null, false, "b20517ec-cd05-4087-88bf-cd17704f559b", "")
            {
                _contentiframe1 = new EPM_CRM_PQRRepositoryFolders.ContentIFrame1Folder(this);
                _epmpqrservicepointidleditInfo = new RepoItemInfo(this, "EpmPqrservicepointidLedit", ".//iframe[#'contentIFrame1']//span[#'epm_pqrservicepointid_cl']", 30000, null, "7a02db37-a839-477d-abd7-03d10af74665");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b20517ec-cd05-4087-88bf-cd17704f559b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b20517ec-cd05-4087-88bf-cd17704f559b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EpmPqrservicepointidLedit item.
            /// </summary>
            [RepositoryItem("7a02db37-a839-477d-abd7-03d10af74665")]
            public virtual Ranorex.SpanTag EpmPqrservicepointidLedit
            {
                get
                {
                    return _epmpqrservicepointidleditInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The EpmPqrservicepointidLedit item info.
            /// </summary>
            [RepositoryItemInfo("7a02db37-a839-477d-abd7-03d10af74665")]
            public virtual RepoItemInfo EpmPqrservicepointidLeditInfo
            {
                get
                {
                    return _epmpqrservicepointidleditInfo;
                }
            }

            /// <summary>
            /// The ContentIFrame1 folder.
            /// </summary>
            [RepositoryFolder("2b9c400a-7c26-46e8-bbad-de7f7d99364e")]
            public virtual EPM_CRM_PQRRepositoryFolders.ContentIFrame1Folder ContentIFrame1
            {
                get { return _contentiframe1; }
            }
        }

        /// <summary>
        /// The ContentIFrame1Folder folder.
        /// </summary>
        [RepositoryFolder("2b9c400a-7c26-46e8-bbad-de7f7d99364e")]
        public partial class ContentIFrame1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _mscrminlinevaluemscrminlinelookup1Info;
            RepoItemInfo _epmpqrservicepointidInfo;
            RepoItemInfo _mscrminlinevaluemscrminlinelookupInfo;
            RepoItemInfo _cl98ccr80c30Info;
            RepoItemInfo _formselectordropdownInfo;
            RepoItemInfo _quejasInfo;
            RepoItemInfo _casoquejasInfo;
            RepoItemInfo _casoquejas2Info;
            RepoItemInfo _mscrmfloatingdivInfo;
            RepoItemInfo _readoptimisedformrefreshformInfo;
            RepoItemInfo _epmpqrservicepointidleditInfo;
            RepoItemInfo _mscrmilmenuInfo;
            RepoItemInfo _customeridInfo;
            RepoItemInfo _mscrminlinevaluemscrminlinehaserrInfo;
            RepoItemInfo _direccionderespuestalabelInfo;
            RepoItemInfo _departamentoderespuestalabelInfo;
            RepoItemInfo _municipioderespuestalabelInfo;
            RepoItemInfo _mscrminlinevaluemscrminlineedithiInfo;
            RepoItemInfo _divtag70daedd7aebd46953c5acbb022d4eInfo;
            RepoItemInfo _epmpqrfilenumberiInfo;
            RepoItemInfo _motivopqrdetallelabelInfo;
            RepoItemInfo _epmpqrteamprocessleditInfo;

            /// <summary>
            /// Creates a new ContentIFrame1  folder.
            /// </summary>
            public ContentIFrame1Folder(RepoGenBaseFolder parentFolder) :
                    base("ContentIFrame1", ".//iframe[#'contentIFrame1']", parentFolder, 30000, null, false, "2b9c400a-7c26-46e8-bbad-de7f7d99364e", "")
            {
                _mscrminlinevaluemscrminlinelookup1Info = new RepoItemInfo(this, "MsCrmInlineValueMsCrmInlineLookup1", ".//div[#'customerid']/div[1]", 30000, null, "a98e2908-c5dd-4224-be94-842a7611bac2");
                _epmpqrservicepointidInfo = new RepoItemInfo(this, "EpmPqrservicepointid", ".//div[#'epm_pqrservicepointid']", 30000, null, "7bcb7da9-5ebf-43bb-8a9d-44ca3dd3235c");
                _mscrminlinevaluemscrminlinelookupInfo = new RepoItemInfo(this, "MsCrmInlineValueMsCrmInlineLookup", ".//div[#'epm_pqrservicepointid']/div[1]", 30000, null, "ed9145bd-330b-4db9-90bf-bc67cdaada96");
                _cl98ccr80c30Info = new RepoItemInfo(this, "CL98CCR80C30", ".//li[#'item84']/a[@title='CL 98 C CR 80 C -30']", 30000, null, "57212a16-6974-4623-bd6a-988862c4266c");
                _formselectordropdownInfo = new RepoItemInfo(this, "FormSelectorDropdown", ".//img[#'formSelectorDropdown']", 30000, null, "32cf43a8-e268-4691-827f-86b5c98b8560");
                _quejasInfo = new RepoItemInfo(this, "Quejas", ".//li[#'27f20a9f-e80a-4e50-b132-85442b0bc86d']//span[@title='Quejas']", 30000, null, "7493229d-a178-4420-8925-820f40c48392");
                _casoquejasInfo = new RepoItemInfo(this, "CasoQuejas", ".//a[#'header_crmFormSelector']/?/?/span[@innertext='Caso : ']", 30000, null, "a87c4e15-862d-4074-ade5-cdcd252bbd60");
                _casoquejas2Info = new RepoItemInfo(this, "CasoQuejas2", ".//a[#'header_crmFormSelector']/?/?/span[@innertext='Caso : Quejas']", 30000, null, "0f80a8c7-d38a-4fac-bc1b-6c844dce62dc");
                _mscrmfloatingdivInfo = new RepoItemInfo(this, "MsCrmFloatingDiv", "body/div[8]", 30000, null, "e5f03900-9382-47a1-b8e8-7ed248412518");
                _readoptimisedformrefreshformInfo = new RepoItemInfo(this, "ReadOptimisedFormRefreshForm", "body", 30000, null, "1854af21-cb4c-46cf-8f4a-4e1d73a11601");
                _epmpqrservicepointidleditInfo = new RepoItemInfo(this, "EpmPqrservicepointidLedit", ".//input[#'epm_pqrservicepointid_ledit']", 30000, null, "c6e88203-5c55-46c4-844b-468b346cbf29");
                _mscrmilmenuInfo = new RepoItemInfo(this, "MsCrmILMenu", ".//div[#'Dialog_epm_pqrservicepointid_IMenu']/div[2]", 30000, null, "329ba423-421e-437d-b382-a691429dcf66");
                _customeridInfo = new RepoItemInfo(this, "Customerid", ".//div[#'customerid']", 30000, null, "bfbd3db3-7428-4c04-a7b6-fa3d7671a11f");
                _mscrminlinevaluemscrminlinehaserrInfo = new RepoItemInfo(this, "MsCrmInlineValueMsCrmInlineHasErr", ".//div[#'epm_pqrcontractnumber']/div[1]", 30000, null, "381bb3b1-5ea2-4d29-a4d7-af8b3b2c4d94");
                _direccionderespuestalabelInfo = new RepoItemInfo(this, "DireccionDeRespuestaLabel", ".//label[#'Dirección de Respuesta_label']", 30000, null, "856af7dd-9cd5-4a40-bd7e-ded274c7a9fc");
                _departamentoderespuestalabelInfo = new RepoItemInfo(this, "DepartamentoDeRespuestaLabel", ".//label[#'Departamento de Respuesta_label']", 30000, null, "ec8c25b6-4c83-4b33-89b8-3613c327d810");
                _municipioderespuestalabelInfo = new RepoItemInfo(this, "MunicipioDeRespuestaLabel", ".//label[#'Municipio de Respuesta_label']", 30000, null, "b18d64a7-9e08-481f-8537-7414ae8c1046");
                _mscrminlinevaluemscrminlineedithiInfo = new RepoItemInfo(this, "MsCrmInlineValueMsCrmInlineEditHi", ".//div[#'epm_pqrfilenumber']/div[1]", 30000, null, "90f019d0-e6f0-41af-ac3f-6ff2b6b2856e");
                _divtag70daedd7aebd46953c5acbb022d4eInfo = new RepoItemInfo(this, "DivTag70daedd7Aebd46953c5aCbb022d4e", ".//div[#'{70daedd7-aebd-4695-3c5a-cbb022d4e380}_Header']", 30000, null, "e55795ca-e05c-4467-bc09-96fd26c4d6c9");
                _epmpqrfilenumberiInfo = new RepoItemInfo(this, "EpmPqrfilenumberI", ".//input[#'epm_pqrfilenumber_i']", 30000, null, "84a20855-2d5e-496d-b9cc-cb9c47b88737");
                _motivopqrdetallelabelInfo = new RepoItemInfo(this, "MotivoPQRDetalleLabel", ".//label[#'Motivo PQR (Detalle)_label']", 30000, null, "12d1adfd-da4e-4151-a66d-608996fb4a59");
                _epmpqrteamprocessleditInfo = new RepoItemInfo(this, "EpmPqrteamprocessLedit", ".//div[#'crmForm']", 30000, null, "6af09b51-31ca-4424-875e-b98ac19acfa6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2b9c400a-7c26-46e8-bbad-de7f7d99364e")]
            public virtual Ranorex.IFrameTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.IFrameTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2b9c400a-7c26-46e8-bbad-de7f7d99364e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MsCrmInlineValueMsCrmInlineLookup1 item.
            /// </summary>
            [RepositoryItem("a98e2908-c5dd-4224-be94-842a7611bac2")]
            public virtual Ranorex.DivTag MsCrmInlineValueMsCrmInlineLookup1
            {
                get
                {
                    return _mscrminlinevaluemscrminlinelookup1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MsCrmInlineValueMsCrmInlineLookup1 item info.
            /// </summary>
            [RepositoryItemInfo("a98e2908-c5dd-4224-be94-842a7611bac2")]
            public virtual RepoItemInfo MsCrmInlineValueMsCrmInlineLookup1Info
            {
                get
                {
                    return _mscrminlinevaluemscrminlinelookup1Info;
                }
            }

            /// <summary>
            /// The EpmPqrservicepointid item.
            /// </summary>
            [RepositoryItem("7bcb7da9-5ebf-43bb-8a9d-44ca3dd3235c")]
            public virtual Ranorex.DivTag EpmPqrservicepointid
            {
                get
                {
                    return _epmpqrservicepointidInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The EpmPqrservicepointid item info.
            /// </summary>
            [RepositoryItemInfo("7bcb7da9-5ebf-43bb-8a9d-44ca3dd3235c")]
            public virtual RepoItemInfo EpmPqrservicepointidInfo
            {
                get
                {
                    return _epmpqrservicepointidInfo;
                }
            }

            /// <summary>
            /// The MsCrmInlineValueMsCrmInlineLookup item.
            /// </summary>
            [RepositoryItem("ed9145bd-330b-4db9-90bf-bc67cdaada96")]
            public virtual Ranorex.DivTag MsCrmInlineValueMsCrmInlineLookup
            {
                get
                {
                    return _mscrminlinevaluemscrminlinelookupInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MsCrmInlineValueMsCrmInlineLookup item info.
            /// </summary>
            [RepositoryItemInfo("ed9145bd-330b-4db9-90bf-bc67cdaada96")]
            public virtual RepoItemInfo MsCrmInlineValueMsCrmInlineLookupInfo
            {
                get
                {
                    return _mscrminlinevaluemscrminlinelookupInfo;
                }
            }

            /// <summary>
            /// The CL98CCR80C30 item.
            /// </summary>
            [RepositoryItem("57212a16-6974-4623-bd6a-988862c4266c")]
            public virtual Ranorex.ATag CL98CCR80C30
            {
                get
                {
                    return _cl98ccr80c30Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The CL98CCR80C30 item info.
            /// </summary>
            [RepositoryItemInfo("57212a16-6974-4623-bd6a-988862c4266c")]
            public virtual RepoItemInfo CL98CCR80C30Info
            {
                get
                {
                    return _cl98ccr80c30Info;
                }
            }

            /// <summary>
            /// The FormSelectorDropdown item.
            /// </summary>
            [RepositoryItem("32cf43a8-e268-4691-827f-86b5c98b8560")]
            public virtual Ranorex.ImgTag FormSelectorDropdown
            {
                get
                {
                    return _formselectordropdownInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The FormSelectorDropdown item info.
            /// </summary>
            [RepositoryItemInfo("32cf43a8-e268-4691-827f-86b5c98b8560")]
            public virtual RepoItemInfo FormSelectorDropdownInfo
            {
                get
                {
                    return _formselectordropdownInfo;
                }
            }

            /// <summary>
            /// The Quejas item.
            /// </summary>
            [RepositoryItem("7493229d-a178-4420-8925-820f40c48392")]
            public virtual Ranorex.SpanTag Quejas
            {
                get
                {
                    return _quejasInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Quejas item info.
            /// </summary>
            [RepositoryItemInfo("7493229d-a178-4420-8925-820f40c48392")]
            public virtual RepoItemInfo QuejasInfo
            {
                get
                {
                    return _quejasInfo;
                }
            }

            /// <summary>
            /// The CasoQuejas item.
            /// </summary>
            [RepositoryItem("a87c4e15-862d-4074-ade5-cdcd252bbd60")]
            public virtual Ranorex.SpanTag CasoQuejas
            {
                get
                {
                    return _casoquejasInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CasoQuejas item info.
            /// </summary>
            [RepositoryItemInfo("a87c4e15-862d-4074-ade5-cdcd252bbd60")]
            public virtual RepoItemInfo CasoQuejasInfo
            {
                get
                {
                    return _casoquejasInfo;
                }
            }

            /// <summary>
            /// The CasoQuejas2 item.
            /// </summary>
            [RepositoryItem("0f80a8c7-d38a-4fac-bc1b-6c844dce62dc")]
            public virtual Ranorex.SpanTag CasoQuejas2
            {
                get
                {
                    return _casoquejas2Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CasoQuejas2 item info.
            /// </summary>
            [RepositoryItemInfo("0f80a8c7-d38a-4fac-bc1b-6c844dce62dc")]
            public virtual RepoItemInfo CasoQuejas2Info
            {
                get
                {
                    return _casoquejas2Info;
                }
            }

            /// <summary>
            /// The MsCrmFloatingDiv item.
            /// </summary>
            [RepositoryItem("e5f03900-9382-47a1-b8e8-7ed248412518")]
            public virtual Ranorex.DivTag MsCrmFloatingDiv
            {
                get
                {
                    return _mscrmfloatingdivInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MsCrmFloatingDiv item info.
            /// </summary>
            [RepositoryItemInfo("e5f03900-9382-47a1-b8e8-7ed248412518")]
            public virtual RepoItemInfo MsCrmFloatingDivInfo
            {
                get
                {
                    return _mscrmfloatingdivInfo;
                }
            }

            /// <summary>
            /// The ReadOptimisedFormRefreshForm item.
            /// </summary>
            [RepositoryItem("1854af21-cb4c-46cf-8f4a-4e1d73a11601")]
            public virtual Ranorex.BodyTag ReadOptimisedFormRefreshForm
            {
                get
                {
                    return _readoptimisedformrefreshformInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The ReadOptimisedFormRefreshForm item info.
            /// </summary>
            [RepositoryItemInfo("1854af21-cb4c-46cf-8f4a-4e1d73a11601")]
            public virtual RepoItemInfo ReadOptimisedFormRefreshFormInfo
            {
                get
                {
                    return _readoptimisedformrefreshformInfo;
                }
            }

            /// <summary>
            /// The EpmPqrservicepointidLedit item.
            /// </summary>
            [RepositoryItem("c6e88203-5c55-46c4-844b-468b346cbf29")]
            public virtual Ranorex.InputTag EpmPqrservicepointidLedit
            {
                get
                {
                    return _epmpqrservicepointidleditInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The EpmPqrservicepointidLedit item info.
            /// </summary>
            [RepositoryItemInfo("c6e88203-5c55-46c4-844b-468b346cbf29")]
            public virtual RepoItemInfo EpmPqrservicepointidLeditInfo
            {
                get
                {
                    return _epmpqrservicepointidleditInfo;
                }
            }

            /// <summary>
            /// The MsCrmILMenu item.
            /// </summary>
            [RepositoryItem("329ba423-421e-437d-b382-a691429dcf66")]
            public virtual Ranorex.DivTag MsCrmILMenu
            {
                get
                {
                    return _mscrmilmenuInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MsCrmILMenu item info.
            /// </summary>
            [RepositoryItemInfo("329ba423-421e-437d-b382-a691429dcf66")]
            public virtual RepoItemInfo MsCrmILMenuInfo
            {
                get
                {
                    return _mscrmilmenuInfo;
                }
            }

            /// <summary>
            /// The Customerid item.
            /// </summary>
            [RepositoryItem("bfbd3db3-7428-4c04-a7b6-fa3d7671a11f")]
            public virtual Ranorex.DivTag Customerid
            {
                get
                {
                    return _customeridInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Customerid item info.
            /// </summary>
            [RepositoryItemInfo("bfbd3db3-7428-4c04-a7b6-fa3d7671a11f")]
            public virtual RepoItemInfo CustomeridInfo
            {
                get
                {
                    return _customeridInfo;
                }
            }

            /// <summary>
            /// The MsCrmInlineValueMsCrmInlineHasErr item.
            /// </summary>
            [RepositoryItem("381bb3b1-5ea2-4d29-a4d7-af8b3b2c4d94")]
            public virtual Ranorex.DivTag MsCrmInlineValueMsCrmInlineHasErr
            {
                get
                {
                    return _mscrminlinevaluemscrminlinehaserrInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MsCrmInlineValueMsCrmInlineHasErr item info.
            /// </summary>
            [RepositoryItemInfo("381bb3b1-5ea2-4d29-a4d7-af8b3b2c4d94")]
            public virtual RepoItemInfo MsCrmInlineValueMsCrmInlineHasErrInfo
            {
                get
                {
                    return _mscrminlinevaluemscrminlinehaserrInfo;
                }
            }

            /// <summary>
            /// The DireccionDeRespuestaLabel item.
            /// </summary>
            [RepositoryItem("856af7dd-9cd5-4a40-bd7e-ded274c7a9fc")]
            public virtual Ranorex.LabelTag DireccionDeRespuestaLabel
            {
                get
                {
                    return _direccionderespuestalabelInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The DireccionDeRespuestaLabel item info.
            /// </summary>
            [RepositoryItemInfo("856af7dd-9cd5-4a40-bd7e-ded274c7a9fc")]
            public virtual RepoItemInfo DireccionDeRespuestaLabelInfo
            {
                get
                {
                    return _direccionderespuestalabelInfo;
                }
            }

            /// <summary>
            /// The DepartamentoDeRespuestaLabel item.
            /// </summary>
            [RepositoryItem("ec8c25b6-4c83-4b33-89b8-3613c327d810")]
            public virtual Ranorex.LabelTag DepartamentoDeRespuestaLabel
            {
                get
                {
                    return _departamentoderespuestalabelInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The DepartamentoDeRespuestaLabel item info.
            /// </summary>
            [RepositoryItemInfo("ec8c25b6-4c83-4b33-89b8-3613c327d810")]
            public virtual RepoItemInfo DepartamentoDeRespuestaLabelInfo
            {
                get
                {
                    return _departamentoderespuestalabelInfo;
                }
            }

            /// <summary>
            /// The MunicipioDeRespuestaLabel item.
            /// </summary>
            [RepositoryItem("b18d64a7-9e08-481f-8537-7414ae8c1046")]
            public virtual Ranorex.LabelTag MunicipioDeRespuestaLabel
            {
                get
                {
                    return _municipioderespuestalabelInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The MunicipioDeRespuestaLabel item info.
            /// </summary>
            [RepositoryItemInfo("b18d64a7-9e08-481f-8537-7414ae8c1046")]
            public virtual RepoItemInfo MunicipioDeRespuestaLabelInfo
            {
                get
                {
                    return _municipioderespuestalabelInfo;
                }
            }

            /// <summary>
            /// The MsCrmInlineValueMsCrmInlineEditHi item.
            /// </summary>
            [RepositoryItem("90f019d0-e6f0-41af-ac3f-6ff2b6b2856e")]
            public virtual Ranorex.DivTag MsCrmInlineValueMsCrmInlineEditHi
            {
                get
                {
                    return _mscrminlinevaluemscrminlineedithiInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MsCrmInlineValueMsCrmInlineEditHi item info.
            /// </summary>
            [RepositoryItemInfo("90f019d0-e6f0-41af-ac3f-6ff2b6b2856e")]
            public virtual RepoItemInfo MsCrmInlineValueMsCrmInlineEditHiInfo
            {
                get
                {
                    return _mscrminlinevaluemscrminlineedithiInfo;
                }
            }

            /// <summary>
            /// The DivTag70daedd7Aebd46953c5aCbb022d4e item.
            /// </summary>
            [RepositoryItem("e55795ca-e05c-4467-bc09-96fd26c4d6c9")]
            public virtual Ranorex.DivTag DivTag70daedd7Aebd46953c5aCbb022d4e
            {
                get
                {
                    return _divtag70daedd7aebd46953c5acbb022d4eInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DivTag70daedd7Aebd46953c5aCbb022d4e item info.
            /// </summary>
            [RepositoryItemInfo("e55795ca-e05c-4467-bc09-96fd26c4d6c9")]
            public virtual RepoItemInfo DivTag70daedd7Aebd46953c5aCbb022d4eInfo
            {
                get
                {
                    return _divtag70daedd7aebd46953c5acbb022d4eInfo;
                }
            }

            /// <summary>
            /// The EpmPqrfilenumberI item.
            /// </summary>
            [RepositoryItem("84a20855-2d5e-496d-b9cc-cb9c47b88737")]
            public virtual Ranorex.InputTag EpmPqrfilenumberI
            {
                get
                {
                    return _epmpqrfilenumberiInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The EpmPqrfilenumberI item info.
            /// </summary>
            [RepositoryItemInfo("84a20855-2d5e-496d-b9cc-cb9c47b88737")]
            public virtual RepoItemInfo EpmPqrfilenumberIInfo
            {
                get
                {
                    return _epmpqrfilenumberiInfo;
                }
            }

            /// <summary>
            /// The MotivoPQRDetalleLabel item.
            /// </summary>
            [RepositoryItem("12d1adfd-da4e-4151-a66d-608996fb4a59")]
            public virtual Ranorex.LabelTag MotivoPQRDetalleLabel
            {
                get
                {
                    return _motivopqrdetallelabelInfo.CreateAdapter<Ranorex.LabelTag>(true);
                }
            }

            /// <summary>
            /// The MotivoPQRDetalleLabel item info.
            /// </summary>
            [RepositoryItemInfo("12d1adfd-da4e-4151-a66d-608996fb4a59")]
            public virtual RepoItemInfo MotivoPQRDetalleLabelInfo
            {
                get
                {
                    return _motivopqrdetallelabelInfo;
                }
            }

            /// <summary>
            /// The EpmPqrteamprocessLedit item.
            /// </summary>
            [RepositoryItem("6af09b51-31ca-4424-875e-b98ac19acfa6")]
            public virtual Ranorex.DivTag EpmPqrteamprocessLedit
            {
                get
                {
                    return _epmpqrteamprocessleditInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The EpmPqrteamprocessLedit item info.
            /// </summary>
            [RepositoryItemInfo("6af09b51-31ca-4424-875e-b98ac19acfa6")]
            public virtual RepoItemInfo EpmPqrteamprocessLeditInfo
            {
                get
                {
                    return _epmpqrteamprocessleditInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}